---
# Default profile is used when running a single instance completely standalone:
spring:
  application:
    name: myapp-eureka-single-server
  profiles: default
server:
  port: 17001  
eureka:
  environment: dev
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    

# primary, secondary illustrate running 2 intercommunicating instances.  This example has them running

---
spring:
  application:
    name: myapp-eureka-server   
  profiles: primary
server:
  port: 17001  
eureka:
  environment: dev
  instance:
    hostname: localhost       
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://localhost:17002/eureka/

---
spring:
  application:
    name: myapp-eureka-server      
  profiles: secondary
server:
  port: 17002
eureka: 
  environment: dev
  instance:
    hostname: localhost     
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://localhost:17001/eureka/
  